error: False
settings: None
pythonpath: None
verbosity: 1
traceback: False
versions: oTree: 0.7.4 - Django: 1.8.8
export: auto_name
no_color: False
coverage: None
timestamp: 2016-07-21T14:29:08.528000
failures: 0
save: None
session_config_name: ['dimension']
sizes:
	dimension: 97
